language: python

sudo: false
env:
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py34
    - TOXENV=pypy

install:
    - if [[ "$TOXENV" == "py32" ]]; then pip install 'virtualenv<14' ; fi
    - travis_retry pip install tox

script:
    - tox
